const ROUTES = {
  LOGIN: 'LOGIN',
  DASHBOARD: 'DASHBOARD',
  TODO_APP: 'TODO_APP',
  FORTH_SCREEN: 'FORTH_SCREEN',
  IMAGE1_DETAILS: 'IMAGE1_DETAILS',
  WEATHER_APP: 'WEATHER_APP',
  WEATHER_DETAIL: 'WEATHER_DETAIL',
};

export {ROUTES};
