const ROUTES = {
  LOGIN: 'LOGIN',
  DASHBOARD: 'DASHBOARD',
  TODO_APP: 'TODO_APP',
  DASHBOARD_TODO_TAB: 'DASHBOARD_TODO_TAB',
  DESTINATION_UI: 'DESTINATION_UI',
  DESTINATION_DETAIL: 'DESTINATION_DETAIL',
  WEATHER_APP: 'WEATHER_APP',
  WEATHER_DETAIL: 'WEATHER_DETAIL',
  WEATHERAPP_UI: 'WEATHERAPP_UI',
  WEATHER_TAB: 'WEATHER_TAB',
  WeatherUi_Detail: 'WeatherUi_Detail'
};

export {ROUTES};
