const ROUTES = {
  LOGIN: 'LOGIN',
  DASHBOARD: 'DASHBOARD',
  TODO_APP: 'TODO_APP',
  FORTH_SCREEN: 'FORTH_SCREEN',
  WEATHER_APP: 'WEATHER_APP',
  WEATHER_DETAIL: 'WEATHER_DETAIL',
  DESTINATION_DETAIL: 'DESTINATION_DETAIL',
  TAB: 'TAB',
};

export {ROUTES};
